# Generated by Django 6.0.3 on 2026-05-02 13:20

import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Удобство')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
            },
        ),
        migrations.CreateModel(
            name='VenueEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='VenueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип площадки')),
            ],
            options={
                'verbose_name': 'Тип площадки',
                'verbose_name_plural': 'Типы площадок',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название площадки')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('short_description', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('city', models.CharField(default='Новосибирск', max_length=100, verbose_name='Город')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Район')),
                ('metro', models.CharField(blank=True, max_length=100, verbose_name='Ближайшее метро')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('area', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Площадь (кв.м.)')),
                ('max_capacity', models.PositiveIntegerField(verbose_name='Вместимость (макс.)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость аренды')),
                ('price_unit', models.CharField(choices=[('hour', 'В час'), ('day', 'В день'), ('request', 'По запросу')], default='day', max_length=20, verbose_name='Единица стоимости')),
                ('parking', models.BooleanField(default=False, verbose_name='Парковка')),
                ('images', models.ImageField(blank=True, upload_to='venue_images/', verbose_name='Галерея фото')),
                ('video', models.FileField(blank=True, null=True, upload_to='venue_videos/', verbose_name='Видео (опционально)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'Архив')], default='draft', max_length=20)),
                ('placement_tariff', models.CharField(choices=[('basic', 'Базовый'), ('extended', 'Расширенный'), ('premium', 'Премиум')], default='basic', max_length=20)),
                ('contacts_opened', models.BooleanField(default=False, verbose_name='Контакты открыты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('formats', taggit.managers.TaggableManager(help_text='Выберите форматы: тренинг, мастер-класс и т.д.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Подходит для формата')),
                ('amenities', models.ManyToManyField(blank=True, to='venues.venueamenity', verbose_name='Удобства')),
                ('equipment', models.ManyToManyField(blank=True, to='venues.venueequipment', verbose_name='Оборудование')),
                ('venue_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.venuetype', verbose_name='Тип площадки')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('event_date', models.DateTimeField()),
                ('participants_count', models.PositiveIntegerField()),
                ('event_format', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_work', 'В работе'), ('transferred', 'Передана площадке'), ('closed', 'Закрыта')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Заявка на площадку',
                'verbose_name_plural': 'Заявки на площадки',
            },
        ),
    ]
