# Generated by Django 6.0.3 on 2026-06-19 08:13

import core.mixins
import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категория оборудования')),
            ],
            options={
                'verbose_name': 'Категория оборудования',
                'verbose_name_plural': 'Категории оборудования',
            },
        ),
        migrations.CreateModel(
            name='VenueFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Формат площадки')),
            ],
            options={
                'verbose_name': 'Формат площадки',
                'verbose_name_plural': 'Форматы площадок',
            },
        ),
        migrations.CreateModel(
            name='VenueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип площадки')),
            ],
            options={
                'verbose_name': 'Тип площадки',
                'verbose_name_plural': 'Типы площадок',
            },
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название оборудования')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='venues.equipmentcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Элемент оборудования',
                'verbose_name_plural': 'Элементы оборудования',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff', models.PositiveSmallIntegerField(choices=[(1, 'Free'), (2, 'Standard'), (3, 'Premium')], default=1, help_text='Выберите тариф - от него зависят доступные возможности', verbose_name='Тариф')),
                ('title', models.CharField(max_length=255, verbose_name='Название площадки')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('short_description', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('city', models.CharField(default='', max_length=100, verbose_name='Город')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Район')),
                ('metro', models.CharField(blank=True, max_length=100, verbose_name='Ближайшее метро')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('area', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Площадь (кв.м.)')),
                ('max_capacity', models.PositiveIntegerField(verbose_name='Вместимость (макс.)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость аренды')),
                ('price_unit', models.CharField(choices=[('hour', 'В час'), ('day', 'В день'), ('request', 'По запросу')], default='day', max_length=20, verbose_name='Единица стоимости')),
                ('video', models.FileField(blank=True, null=True, upload_to='venue_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi']), core.validators.validate_video_duration], verbose_name='Видео (опционально)')),
                ('processed_video_hash', models.CharField(blank=True, max_length=32, null=True, verbose_name='Хэш обработанного видео площадки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'Архив')], default='draft', max_length=20)),
                ('contacts_opened', models.BooleanField(default=False, verbose_name='Контакты открыты')),
                ('contact_info', models.TextField(blank=True, verbose_name='Контактная информация')),
                ('email', models.EmailField(blank=True, help_text='Email, на который будут приходить уведомления о новых заявках', max_length=254, verbose_name='Email для уведомлений')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('equipment', models.ManyToManyField(blank=True, to='venues.equipmentcategory', verbose_name='Оборудование')),
                ('equipment_items', models.ManyToManyField(blank=True, related_name='venues', to='venues.equipmentitem', verbose_name='Элементы оборудования')),
                ('formats', models.ManyToManyField(blank=True, help_text='Выберите форматы: тренинг, мастер-класс и т.д.', to='venues.venueformat', verbose_name='Форматы площадки')),
                ('venue_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.venuetype', verbose_name='Тип площадки')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
            },
            bases=(core.mixins.VideoWatermarkMixin, core.mixins.ImageWatermarkMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('event_date', models.DateTimeField()),
                ('participants_count', models.PositiveIntegerField()),
                ('event_format', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_work', 'В работе'), ('transferred', 'Передана площадке'), ('closed', 'Закрыта')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Заявка на площадку',
                'verbose_name_plural': 'Заявки на площадки',
            },
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venue_images/', verbose_name='Фото площадки')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venues.venue', verbose_name='Площадка')),
            ],
            options={
                'verbose_name': 'Фото площадки',
                'verbose_name_plural': 'Фото площадок',
            },
            bases=(core.mixins.VideoWatermarkMixin, core.mixins.ImageWatermarkMixin, models.Model),
        ),
    ]
