# Generated by Django 6.0.3 on 2026-05-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Формат мероприятия')),
            ],
            options={
                'verbose_name': 'Формат мероприятия',
                'verbose_name_plural': 'Форматы мероприятий',
            },
        ),
        migrations.AlterField(
            model_name='venue',
            name='formats',
            field=models.ManyToManyField(blank=True, to='venues.venueformat', verbose_name='Подходит для формата'),
        ),
    ]
