# Generated by Django 6.0.3 on 2026-06-19 09:00

import core.image_storage
import core.validators
import core.video_storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='video',
            field=models.FileField(blank=True, null=True, storage=core.video_storage.YandexVideoProcessingStorage(), upload_to='venue_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi']), core.validators.validate_video_duration], verbose_name='Видео (опционально)'),
        ),
        migrations.AlterField(
            model_name='venueimage',
            name='image',
            field=models.ImageField(storage=core.image_storage.YandexImageProcessingStorage(), upload_to='venue_images/', verbose_name='Фото площадки'),
        ),
    ]
