# Generated by Django 6.0.3 on 2026-05-09 09:18

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE TABLE venues_venue_formats ("
            "id SERIAL NOT NULL PRIMARY KEY, "
            "venue_id INTEGER NOT NULL, "
            "venueformat_id INTEGER NOT NULL, "
            "CONSTRAINT venues_venue_formats_venue_id_venueformat_id_72b70d4a_uniq UNIQUE (venue_id, venueformat_id), "
            "CONSTRAINT venues_venue_formats_venue_id_108a112f_fk_venues_ FOREIGN KEY (venue_id) "
            "REFERENCES venues_venue (id) DEFERRABLE INITIALLY DEFERRED, "
            "CONSTRAINT venues_venue_formats_venueformat_id_108a112f_fk_ve FOREIGN KEY (venueformat_id) "
            "REFERENCES venues_venueformat (id) DEFERRABLE INITIALLY DEFERRED"
            ");"
        ),
    ]