# Generated by Django 6.0.3 on 2026-05-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_create_venue_formats_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='email',
            field=models.EmailField(blank=True, help_text='Email, на который будут приходить уведомления о новых заявках', max_length=254, verbose_name='Email для уведомлений'),
        ),
    ]
