# Generated by Django 6.0.3 on 2026-07-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_alter_venue_video_alter_venueimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Максимум 1500 символов', verbose_name='Описание'),
        ),
    ]
