# Generated by Django 6.0.3 on 2026-05-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venueformat_alter_venue_formats'),
    ]

    operations = [
    ]
