# Generated by Django 6.0.3 on 2026-05-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_create_equipmentitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='equipment_items',
            field=models.ManyToManyField(blank=True, related_name='venues', to='venues.equipmentitem', verbose_name='Элементы оборудования'),
        ),
    ]
