# Generated by Django 6.0.3 on 2026-06-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venue_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='processed_video_hash',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Хэш обработанного видео площадки'),
        ),
    ]
