# Generated by Django 6.0.3 on 2026-05-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_alter_venue_formats_alter_venue_images'),
    ]

    operations = [
    ]
