# Generated by Django 5.2 on 2026-06-14 04:57

from django.db import migrations, models
import core.image_storage

class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_alter_venue_processed_video_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueimage',
            name='image',
            field=models.ImageField(storage=core.image_storage.YandexImageProcessingStorage(), upload_to='venue_images/', verbose_name='Фото'),
        ),
    ]
