# Generated by Django 5.2 on 2026-09-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_bookingrequest_session_key_bookingrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueimage',
            name='image_processing_status',
            field=models.CharField(default='pending', max_length=50, verbose_name='Статус обработки изображения'),
        ),
        migrations.AddField(
            model_name='venueimage',
            name='processed_image_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Хэш обработанного изображения'),
        ),
    ]
