# Generated by Django 5.2 on 2026-09-18 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_sync_venueimage_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueAdditionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=255, verbose_name='Название площадки')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес площадки')),
                ('applicant_name', models.CharField(max_length=255, verbose_name='Имя заявителя')),
                ('applicant_phone', models.CharField(max_length=30, verbose_name='Телефон заявителя')),
                ('applicant_email', models.EmailField(max_length=254, verbose_name='Email заявителя')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_work', 'В работе'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_addition_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на добавление площадки',
                'verbose_name_plural': 'Заявки на добавление площадок',
                'ordering': ('-created_at',),
            },
        ),
    ]
