# Generated by Django 6.0.3 on 2026-05-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_auto_20260502_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='formats',
            field=models.ManyToManyField(blank=True, to='venues.venueformat', verbose_name='Подходит для формата'),
        ),
    ]
