# Generated by Django 6.0.3 on 2026-09-19 06:49

import core.validators
import core.video_storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_venueadditionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='video',
            field=models.FileField(blank=True, null=True, storage=core.video_storage.YandexVideoProcessingStorage(subdirectory='venue_videos'), upload_to='venue_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi']), core.validators.validate_video_duration], verbose_name='Видео (опционально)'),
        ),
    ]
