# Generated by Django 6.0.3 on 2026-05-02 20:17

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('venues', '0006_alter_venue_formats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='formats',
            field=taggit.managers.TaggableManager(help_text='Выберите форматы: тренинг, мастер-класс и т.д.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Подходит для формата'),
        ),
    ]
