# Generated by Django 6.0.3 on 2026-09-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_alter_venue_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='video_processing_status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Обработка завершена'), ('failed', 'Ошибка обработки')], default='pending', max_length=20, verbose_name='Статус обработки видео'),
        ),
    ]
