# Generated by Django 5.2 on 2026-09-27 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_venue_video_processing_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venueadditionrequest',
            options={'verbose_name': 'Заявка на добавление площадки', 'verbose_name_plural': 'Заявки на добавление площадок'},
        ),
        migrations.CreateModel(
            name='VenueView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=40, verbose_name='Ключ сессии (для анонимов)')),
                ('source', models.CharField(blank=True, default='', max_length=255, verbose_name='Источник перехода')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время перехода')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_views', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (если авторизован)')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='venues.venue', verbose_name='Площадка')),
            ],
            options={
                'verbose_name': 'Переход на площадку',
                'verbose_name_plural': 'Переходы на площадки',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['venue', 'viewed_at'], name='venues_venu_venue_i_11440c_idx')],
            },
        ),
    ]
