# Generated by Django 6.0.3 on 2026-05-03 09:13

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_alter_venue_latitude_alter_venue_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='processed_video_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='Хэш обработанного видео'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='venue_images/', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='venue_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi']), core.validators.validate_video_duration], verbose_name='Видео (опционально)'),
        ),
    ]
