# Generated by Django 6.0.3 on 2026-05-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_venue_processed_video_hash_alter_venue_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Город'),
        ),
    ]
