# Generated by Django 6.0.3 on 2026-05-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0010_alter_venue_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='placement_tariff',
        ),
        migrations.AddField(
            model_name='venue',
            name='tariff',
            field=models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], default='free', help_text='Выберите тариф - от него зависят доступные возможности', max_length=20, verbose_name='Тариф'),
        ),
    ]
