# Generated by Django 6.0.3 on 2026-05-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0011_remove_venue_placement_tariff_venue_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='tariff',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Free'), (2, 'Standard'), (3, 'Premium')], default=1, help_text='Выберите тариф - от него зависят доступные возможности', verbose_name='Тариф'),
        ),
    ]
