# Generated by Django 6.0.3 on 2026-05-04 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0012_alter_venue_tariff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='images',
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venue_images/', verbose_name='Фото')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Альтернативный текст')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venues.venue', verbose_name='Площадка')),
            ],
            options={
                'verbose_name': 'Фото площадки',
                'verbose_name_plural': 'Фото площадок',
            },
        ),
    ]
