# Generated by Django 6.0.3 on 2026-05-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0013_remove_venue_images_venueimage'),
    ]

    operations = [
        # Поле 'order' уже существует в базе данных, пропускаем добавление
        migrations.RunSQL("SELECT 1;", reverse_sql="SELECT 1;"),
    ]
