# Generated by Django 6.0.3 on 2026-05-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0013_remove_venue_images_venueimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
