# Generated by Django 6.0.3 on 2026-05-06 12:26

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0014_venueimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]