# Generated by Django 6.0.3 on 2026-05-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0015_venueimage_order_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueimage',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='venueimage',
            name='order',
        ),
    ]
