# Generated by Django 6.0.3 on 2026-05-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0016_remove_venueimage_alt_text_remove_venueimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='Wi-Fi'),
        ),
    ]
