# Generated by Django 6.0.3 on 2026-05-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0017_venue_has_wifi'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='contact_info',
            field=models.TextField(blank=True, verbose_name='Контактная информация'),
        ),
    ]
