# Generated by Django 6.0.3 on 2026-05-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0018_venue_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueEquipmentAndAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Оборудование и удобства')),
            ],
            options={
                'verbose_name': 'Оборудование и удобства',
                'verbose_name_plural': 'Оборудование и удобства',
            },
        ),
        migrations.RemoveField(
            model_name='venue',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='equipment',
        ),
        migrations.AddField(
            model_name='venue',
            name='equipment_amenity',
            field=models.ManyToManyField(blank=True, to='venues.venueequipmentandamenity', verbose_name='Оборудование и удобства'),
        ),
        migrations.DeleteModel(
            name='VenueAmenity',
        ),
        migrations.DeleteModel(
            name='VenueEquipment',
        ),
    ]
