# Generated by Django 6.0.3 on 2026-06-19 08:12

import core.mixins
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название пакета')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена пакета')),
                ('max_active_events', models.PositiveIntegerField(default=1, verbose_name='Максимум активных мероприятий')),
                ('event_card_type', models.CharField(choices=[('basic', 'Базовая'), ('extended', 'Расширенная'), ('priority', 'Приоритетная')], default='basic', max_length=20, verbose_name='Тип карточки события')),
                ('description_type', models.CharField(choices=[('short', 'Краткое'), ('detailed', 'Подробное')], default='short', max_length=20, verbose_name='Тип описания')),
                ('has_program_and_speakers', models.BooleanField(default=True, verbose_name='Программа и спикеры')),
                ('max_photos', models.PositiveIntegerField(default=1, verbose_name='Максимум фото')),
                ('has_video', models.BooleanField(default=False, verbose_name='Видео')),
                ('has_platform_request', models.BooleanField(default=True, verbose_name='Заявка внутри платформы')),
                ('has_free_registration', models.BooleanField(default=True, verbose_name='Зарегистрироваться (бесплатное мероприятие)')),
                ('has_ticket_sales', models.BooleanField(default=True, verbose_name='Покупка билета')),
                ('visibility_level', models.CharField(choices=[('basic', 'Базовая'), ('enhanced', 'Повышенная'), ('priority', 'Приоритетная')], default='basic', max_length=20, verbose_name='Видимость в каталоге')),
                ('has_collection_participation', models.BooleanField(default=False, verbose_name='Участие в подборках')),
                ('is_monthly', models.BooleanField(default=False, verbose_name='Ежемесячная подписка')),
            ],
            options={
                'verbose_name': 'Пакет мероприятия',
                'verbose_name_plural': 'Пакеты мероприятий',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название формата')),
            ],
            options={
                'verbose_name': 'Формат',
                'verbose_name_plural': 'Форматы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MainTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название основного тега')),
            ],
            options={
                'verbose_name': 'Основной тег',
                'verbose_name_plural': 'Основные теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('guest', 'Гость'), ('visitor', 'Посетитель'), ('partner', 'Партнёр')], default='guest', max_length=10, verbose_name='Тип пользователя')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Логин')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('verification_status', models.CharField(choices=[('not_submitted', 'Не отправлено'), ('pending', 'На рассмотрении'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='not_submitted', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо (ФИО)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='user_logos/')),
                ('social_links', models.TextField(blank=True, null=True)),
                ('video_business_card', models.FileField(blank=True, help_text='Максимальная длительность видео: 5 минут.', null=True, upload_to='partner_video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])], verbose_name='Видео (загрузить)')),
                ('processed_video_business_card_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('video_business_card_processing_status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Обработка завершена'), ('failed', 'Ошибка обработки')], default='pending', max_length=20, verbose_name='Статус обработки видео-визитки')),
                ('video_processing_status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Обработка завершена'), ('failed', 'Ошибка обработки')], default='pending', max_length=20, verbose_name='Статус обработки видео')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=(models.Model, core.mixins.VideoWatermarkMixin),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VisitorUser',
            fields=[
            ],
            options={
                'verbose_name': 'Обычный пользователь',
                'verbose_name_plural': 'Обычные пользователи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='Код подтверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код подтверждения почты',
                'verbose_name_plural': 'Коды подтверждения почты',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Максимум 100 символов', max_length=100, verbose_name='Название')),
                ('description', models.TextField(help_text='Максимум 300 символов', max_length=1500, verbose_name='Описание')),
                ('date_time', models.DateTimeField(help_text='Мероприятие должно быть не ранее чем через 24 часа от текущего момента', verbose_name='Дата и время')),
                ('place_data', models.JSONField(blank=True, help_text='Данные о местоположении в формате JSON (координаты, адрес, дополнительная информация)', null=True, verbose_name='Данные о местоположении')),
                ('video_processing_status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Обработка завершена'), ('failed', 'Ошибка обработки')], default='pending', max_length=20, verbose_name='Статус обработки видео')),
                ('status', models.CharField(choices=[('on_moderation', 'На модерации'), ('active', 'Активно'), ('completed', 'Завершено'), ('rejected', 'Отклонено')], default='on_moderation', max_length=20, verbose_name='Статус')),
                ('refund_deadline_hours', models.PositiveIntegerField(default=24, help_text='Укажите, за сколько часов до начала мероприятия можно вернуть билет', verbose_name='Срок возврата билетов (часы до начала)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Изображение')),
                ('video_url', models.FileField(blank=True, help_text='Максимальная длительность видео: 5 минут.', null=True, upload_to='event_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])], verbose_name='Видео (загрузить)')),
                ('processed_video_url_hash', models.CharField(blank=True, max_length=32, null=True, verbose_name='Хэш обработанного видео мероприятия')),
                ('program_file', models.FileField(blank=True, null=True, upload_to='event_programs/', verbose_name='Программа (PDF)')),
                ('allow_booking_without_payment', models.BooleanField(default=False, verbose_name='Разрешить бронирование без оплаты')),
                ('allow_platform_requests', models.BooleanField(default=False, help_text='Если включено, пользователи смогут оставить заявку с вопросами', verbose_name='Разрешить заявки через платформу')),
                ('auto_close_sales_hours', models.PositiveIntegerField(default=0, help_text='0 - не закрывать автоматически', verbose_name='Закрыть продажи за (часов)')),
                ('duration', models.CharField(blank=True, help_text='Формат: ЧЧ:ММ (например, 02:30 для 2 часов 30 минут)', max_length=5, null=True, verbose_name='Длительность (ЧЧ:ММ)')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Комиссия (%)')),
                ('has_sold_tickets', models.BooleanField(default=False, help_text='Флаг, указывающий, что на мероприятие проданы билеты', verbose_name='Проданы билеты')),
                ('rejection_reason', models.TextField(blank=True, help_text='Причина, по которой мероприятие было отклонено модератором', null=True, verbose_name='Причина отклонения')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
                ('package', models.ForeignKey(blank=True, help_text='Выберите пакет для мероприятия', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventpackage', verbose_name='Пакет мероприятия')),
                ('format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.format', verbose_name='Формат')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-date_time'],
            },
            bases=(models.Model, core.mixins.VideoWatermarkMixin, core.mixins.ImageWatermarkMixin),
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/', verbose_name='Фото мероприятия')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Фото мероприятия',
                'verbose_name_plural': 'Фото мероприятий',
            },
            bases=(core.mixins.VideoWatermarkMixin, core.mixins.ImageWatermarkMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PartnerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='partner_documents/', verbose_name='Документ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Подтверждено модератором')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Причина отклонения')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Документ партнёра',
                'verbose_name_plural': 'Документы партнёров',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('sberbank', 'Сбербанк'), ('tinkoff', 'Тинькофф'), ('vtb', 'ВТБ'), ('alfabank', 'Альфа-Банк'), ('other', 'Другой банк')], max_length=100, verbose_name='Банк')),
                ('account_number', models.CharField(max_length=50, verbose_name='Номер счёта/карты')),
                ('account_holder', models.CharField(max_length=255, verbose_name='Владелец счёта')),
                ('inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН')),
                ('is_default', models.BooleanField(default=False, verbose_name='Основные реквизиты')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Реквизиты для выплаты',
                'verbose_name_plural': 'Реквизиты для выплат',
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма к выплате')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В обработке'), ('paid', 'Выплачено'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
                ('payment_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payoutdetails', verbose_name='Реквизиты')),
            ],
            options={
                'verbose_name': 'Запрос на выплату',
                'verbose_name_plural': 'Запросы на выплату',
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_user', models.BooleanField(default=True)),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='support_attachments/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.supportmessage')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('closed', 'Закрыто')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, help_text='Мероприятие, к которому относится обращение', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.event', verbose_name='Связанное мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.supportticket'),
        ),
        migrations.CreateModel(
            name='EventRequestProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Заявка на мероприятие',
                'verbose_name_plural': 'Заявки на мероприятия',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.supportticket',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название подтега')),
                ('main_tag', models.ForeignKey(default=1, help_text='Основной тег, к которому относится этот подтег', on_delete=django.db.models.deletion.CASCADE, related_name='subtags', to='core.maintag', verbose_name='Основной тег')),
            ],
            options={
                'verbose_name': 'Подтег',
                'verbose_name_plural': 'Подтеги',
                'ordering': ['main_tag__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Выберите до 5 тегов для мероприятия', to='core.tag', verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название билета')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('available_quantity', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_data', models.JSONField(verbose_name='Данные участника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество билетов')),
                ('attended', models.BooleanField(default=False, verbose_name='Посетил мероприятие')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('payment_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок оплаты')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор платежа')),
                ('yookassa_payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор платежа в ЮКассе')),
                ('yookassa_payment_data', models.JSONField(blank=True, null=True, verbose_name='Данные платежа из ЮКассы')),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма комиссии платформы, удержанная с этого заказа', max_digits=10, verbose_name='Комиссия платформы')),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('succeeded', 'Оплачено'), ('canceled', 'Отменено'), ('refunded', 'Возврат'), ('reserved', 'Забронировано')], default='pending', max_length=20, verbose_name='Статус платежа')),
                ('purchase_type', models.CharField(choices=[('paid_ticket', 'Платный билет'), ('free_registration', 'Бесплатная регистрация'), ('platform_request', 'Заявка через платформу')], default='paid_ticket', max_length=20, verbose_name='Тип покупки')),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, null=True, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, null=True, verbose_name='UTM Campaign')),
                ('utm_term', models.CharField(blank=True, max_length=100, null=True, verbose_name='UTM Term')),
                ('utm_content', models.CharField(blank=True, max_length=100, null=True, verbose_name='UTM Content')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.ticket', verbose_name='Билет')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='UserPackageSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала подписки')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания подписки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('subscription_type', models.CharField(choices=[('monthly', 'Ежемесячная подписка')], default='monthly', max_length=20, verbose_name='Тип подписки')),
                ('scheduled_change_date', models.DateTimeField(blank=True, help_text='Дата, когда должен вступить в силу запланированный пакет', null=True, verbose_name='Дата запланированного изменения')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_subscriptions', to='core.eventpackage', verbose_name='Пакет')),
                ('scheduled_change_to', models.ForeignKey(blank=True, help_text='Пакет, на который будет переключена подписка после окончания текущей', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_subscriptions', to='core.eventpackage', verbose_name='Запланированный пакет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на пакет',
                'verbose_name_plural': 'Подписки на пакеты',
            },
        ),
    ]
