# Generated by Django 6.0.3 on 2026-06-19 09:00

import core.document_storage
import core.image_storage
import core.video_storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=core.image_storage.YandexImageProcessingStorage(), upload_to='user_logos/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='video_business_card',
            field=models.FileField(blank=True, help_text='Максимальная длительность видео: 5 минут.', null=True, storage=core.video_storage.YandexVideoProcessingStorage(), upload_to='partner_video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])], verbose_name='Видео (загрузить)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.image_storage.YandexImageProcessingStorage(), upload_to='event_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='program_file',
            field=models.FileField(blank=True, null=True, storage=core.document_storage.YandexDocumentProcessingStorage(), upload_to='event_programs/', verbose_name='Программа (PDF)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='video_url',
            field=models.FileField(blank=True, help_text='Максимальная длительность видео: 5 минут.', null=True, storage=core.video_storage.YandexVideoProcessingStorage(), upload_to='event_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])], verbose_name='Видео (загрузить)'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(storage=core.image_storage.YandexImageProcessingStorage(), upload_to='event_images/', verbose_name='Фото мероприятия'),
        ),
        migrations.AlterField(
            model_name='partnerdocument',
            name='document',
            field=models.FileField(storage=core.document_storage.YandexDocumentProcessingStorage(), upload_to='partner_documents/', verbose_name='Документ'),
        ),
    ]
