# Generated by Django 6.0.3 on 2026-04-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('guest', 'Гость'), ('visitor', 'Посетитель'), ('partner', 'Партнёр')], default='guest', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('on_moderation', 'На модерации'), ('active', 'Активно'), ('completed', 'Завершено'), ('archived', 'Архив')], default='on_moderation', max_length=20, verbose_name='Статус'),
        ),
    ]
