# Generated by Django 6.0.3 on 2026-06-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='event',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='event',
            name='metro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ближайшее метро'),
        ),
    ]
