# Generated by Django 6.0.3 on 2026-04-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260417_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='refund_deadline_hours',
            field=models.PositiveIntegerField(default=24, help_text='Укажите, за сколько часов до начала мероприятия можно вернуть билет', verbose_name='Срок возврата билетов (часы до начала)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(help_text='Мероприятие должно быть не ранее чем через 24 часа от текущего момента', verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_full',
            field=models.TextField(help_text='Максимум 3000 символов', max_length=5000, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_short',
            field=models.TextField(help_text='Максимум 300 символов', max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Максимум 100 символов', max_length=100, verbose_name='Название'),
        ),
    ]
