# Generated by Django 5.2 on 2026-04-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='quantity',
            new_name='available_quantity',
        ),
    ]
