# Generated by Django 5.2 on 2026-04-05 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_quantity_ticket_available_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.AddField(
            model_name='event',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Комиссия (%)'),
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма к выплате')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В обработке'), ('paid', 'Выплачено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payout_method', models.JSONField(verbose_name='Реквизиты для выплаты')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос на выплату',
                'verbose_name_plural': 'Запросы на выплату',
            },
        ),
    ]
