# Generated by Django 6.0.3 on 2026-04-07 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_id_alter_customuser_id_alter_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachments/', verbose_name='Прикрепить файл')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('closed', 'Закрыто')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тикет поддержки',
                'verbose_name_plural': 'Тикеты поддержки',
            },
        ),
    ]
