# Generated by Django 6.0.3 on 2026-06-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_address_event_city_event_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_adress',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Дополнение к адресу'),
        ),
    ]
