# Generated by Django 6.0.3 on 2026-04-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_refund_deadline_hours_alter_event_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('on_moderation', 'На модерации'), ('active', 'Активно'), ('completed', 'Завершено'), ('rejected', 'Отклонено')], default='on_moderation', max_length=20, verbose_name='Статус'),
        ),
    ]
