# Generated by Django 6.0.3 on 2026-04-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='Посетил мероприятие'),
        ),
    ]
