# Generated by Django 5.2 on 2026-04-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ticket_options_event_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='user_logos/', verbose_name='Фото / Логотип'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_links',
            field=models.TextField(blank=True, null=True, verbose_name='Соцсети'),
        ),
    ]
