# Generated by Django 6.0.3 on 2026-06-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_additional_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Максимум 1500 символов', max_length=1500, verbose_name='Краткое описание'),
        ),
    ]
