# Generated by Django 6.0.3 on 2026-04-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_is_verified_partnerdocument'),
        ('core', '0005_alter_category_id_alter_customuser_id_alter_event_id_and_more'),
    ]

    operations = [
    ]
