# Generated by Django 5.2 on 2026-04-14 19:23

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='video_business_card',
            field=models.FileField(blank=True, null=True, upload_to='partner_video_business_cards/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi']), core.validators.validate_and_compress_video], verbose_name='Видеовизитка'),
        ),
        migrations.AlterField(
            model_name='event',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='event_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi']), core.validators.validate_and_compress_video], verbose_name='Видео (загрузить)'),
        ),
    ]
