# Generated by Django 6.0.3 on 2026-06-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price_description',
            field=models.TextField(blank=True, default='', help_text='Описание билета', max_length=100, verbose_name='Описание цены'),
        ),
    ]
