# Generated by Django 6.0.3 on 2026-04-13 16:18

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='video_intro',
            field=models.FileField(blank=True, null=True, upload_to='partner_intros/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi']), core.models.validate_video_duration], verbose_name='Видео-визитка'),
        ),
    ]
