# Generated by Django 6.0.3 on 2026-04-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_is_paid_order_payment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='processed_video_business_card_hash',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Хэш обработанного видео визитки'),
        ),
        migrations.AddField(
            model_name='event',
            name='processed_video_url_hash',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Хэш обработанного видео мероприятия'),
        ),
    ]
