# Generated by Django 5.2 on 2026-04-14 19:34

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customuser_video_business_card_alter_event_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='video_business_card',
        ),
        migrations.AddField(
            model_name='customuser',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='partner_video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi']), core.validators.validate_and_compress_video], verbose_name='Видео (загрузить)'),
        ),
    ]
