# Generated by Django 6.0.3 on 2026-04-24 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='processed_video_business_card_hash',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Хэш обработанного видео визитки'),
        ),
        migrations.AddField(
            model_name='event',
            name='has_sold_tickets',
            field=models.BooleanField(default=False, help_text='Флаг, указывающий, что на мероприятие проданы билеты', verbose_name='Проданы билеты'),
        ),
        migrations.AddField(
            model_name='event',
            name='processed_video_url_hash',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Хэш обработанного видео мероприятия'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Мероприятие, к которому относится обращение', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.event', verbose_name='Связанное мероприятие'),
        ),
    ]
