# Generated by Django 5.2 on 2026-06-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_event_has_sold_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_per_person',
            field=models.BooleanField(default=False, help_text="Отметьте для групповых билетов (от 5 чел.) — цена будет отображаться как 'руб/чел'", verbose_name='Цена за человека'),
        ),
    ]
