# Generated by Django 6.0.3 on 2026-04-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser_processed_video_business_card_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='processed_video_business_card_hash',
        ),
        migrations.AddField(
            model_name='customuser',
            name='processed_video_business_card_hash',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Хэш обработанного видео визитки'),
        ),
    ]
