# Generated by Django 5.2 on 2026-06-24 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ticket_is_per_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.PositiveIntegerField(default=1, verbose_name='Номер билета')),
                ('attended', models.BooleanField(default=False, verbose_name='Посетил мероприятие')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Билет заказа',
                'verbose_name_plural': 'Билеты заказов',
                'ordering': ['ticket_number'],
            },
        ),
    ]
