# Generated by Django 6.0.3 on 2026-04-24 10:11

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fix_processed_video_business_card_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_sold_tickets',
            field=models.BooleanField(default=False, help_text='Флаг, указывающий, что на мероприятие проданы билеты', verbose_name='Проданы билеты'),
        ),
    ]