# Generated by Django 6.0.3 on 2026-04-24 10:38

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_missing_has_sold_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Мероприятие, к которому относится обращение', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.event', verbose_name='Связанное мероприятие'),
        ),
    ]