# Generated by Django 5.2 on 2026-06-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orderticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='processed_video_business_card_hash',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='social_links',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='video_business_card',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='video_business_card_processing_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='video_processing_status',
        ),
    ]
