# Generated by Django 6.0.3 on 2026-04-24 12:17

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_event_to_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place_coordinates',
            field=models.CharField(blank=True, help_text='Координаты в формате широта,долгота', max_length=50, null=True, verbose_name='Координаты места'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='video_business_card',
            field=models.FileField(blank=True, help_text='Максимальная длительность видео: 5 минут.', null=True, upload_to='partner_video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi']), core.validators.validate_video_duration], verbose_name='Видео (загрузить)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='video_url',
            field=models.FileField(blank=True, help_text='Максимальная длительность видео: 5 минут.', null=True, upload_to='event_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi']), core.validators.validate_video_duration], verbose_name='Видео (загрузить)'),
        ),
    ]
