# Generated by Django 5.2 on 2026-06-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_customuser_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Функции, доступные партнёру: создание ивентов, отчёты, выплаты и т.д.', verbose_name='Права доступа'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Причина, по которой заявка партнёра была отклонена', null=True, verbose_name='Причина отказа'),
        ),
    ]
