# Generated by Django 5.2 on 2026-07-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customuser_permissions_customuser_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Минимальное количество билетов, которое можно купить за один раз (1 = без ограничений)', verbose_name='Мин. количество для покупки'),
        ),
    ]
