# Generated by Django 6.0.3 on 2026-04-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_event_place_coordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
        migrations.RemoveField(
            model_name='event',
            name='place_coordinates',
        ),
        migrations.AddField(
            model_name='event',
            name='place_data',
            field=models.JSONField(blank=True, help_text='Данные о местоположении в формате JSON (координаты, адрес, дополнительная информация)', null=True, verbose_name='Данные о местоположении'),
        ),
    ]
