# Generated by Django 6.0.3 on 2026-04-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_event_place_remove_event_place_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_processing_status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Обработка завершена'), ('failed', 'Ошибка обработки')], default='pending', max_length=20, verbose_name='Статус обработки видео'),
        ),
    ]
