# Generated by Django 6.0.3 on 2026-07-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ticket_min_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpackage',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='eventpackage',
            name='priority_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание приоритета'),
        ),
    ]
