# Generated by Django 5.2 on 2026-07-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_eventpackage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organizer_rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения документов организатора'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organizer_status',
            field=models.CharField(choices=[('none', 'Нет отметки'), ('pending', 'На рассмотрении'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='none', max_length=20, verbose_name='Статус проверенного организатора'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_status',
            field=models.CharField(choices=[('not_submitted', 'Не отправлено'), ('pending', 'На рассмотрении'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='not_submitted', max_length=20, verbose_name='Статус партнёра'),
        ),
    ]
