# Generated by Django 6.0.3 on 2026-04-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_event_video_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.CharField(blank=True, help_text='Формат: ЧЧ:ММ (например, 02:30 для 2 часов 30 минут)', max_length=5, null=True, verbose_name='Длительность (ЧЧ:ММ)'),
        ),
    ]
