# Generated by Django 6.0.3 on 2026-07-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_customuser_organizer_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_strict_moderation',
            field=models.BooleanField(default=False, verbose_name='Требует строгой модерации'),
        ),
    ]
