# Generated by Django 6.0.3 on 2026-04-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_event_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.DurationField(blank=True, help_text='Формат: ЧЧ:ММ (например, 02:30 для 2 часов 30 минут)', null=True, verbose_name='Длительность (ЧЧ:ММ)'),
        ),
    ]
