# Generated by Django 5.2 on 2026-08-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_eventimage_image_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='balance_at_request',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Баланс партнёра на момент запроса'),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='rejection_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий администратора при отклонении'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий партнёра'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В обработке'), ('paid', 'Выплачено'), ('rejected', 'Отклонено')], default='processing', max_length=20),
        ),
    ]
