# Generated by Django 6.0.3 on 2026-04-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_event_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='user_logos/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='processed_video_business_card_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='social_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_status',
            field=models.CharField(choices=[('not_submitted', 'Не отправлено'), ('pending', 'На рассмотрении'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='not_submitted', max_length=20),
        ),
    ]
