# Generated by Django 6.0.3 on 2026-05-06 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_customuser_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payoutrequest',
            name='payout_method',
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.CreateModel(
            name='PayoutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('sberbank', 'Сбербанк'), ('tinkoff', 'Тинькофф'), ('vtb', 'ВТБ'), ('alfabank', 'Альфа-Банк'), ('other', 'Другой банк')], max_length=100, verbose_name='Банк')),
                ('account_number', models.CharField(max_length=50, verbose_name='Номер счёта/карты')),
                ('account_holder', models.CharField(max_length=255, verbose_name='Владелец счёта')),
                ('inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН')),
                ('is_default', models.BooleanField(default=False, verbose_name='Основные реквизиты')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Реквизиты для выплаты',
                'verbose_name_plural': 'Реквизиты для выплат',
            },
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='payment_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payoutdetails', verbose_name='Реквизиты'),
        ),
    ]
