# Generated by Django 6.0.3 on 2026-08-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_payoutrequest_balance_at_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='ticket_type',
            field=models.CharField(choices=[('participant', 'Чат с участниками'), ('support', 'Техническая поддержка')], default='support', max_length=20, verbose_name='Тип тикета'),
        ),
    ]
