# Generated by Django 5.2 on 2026-08-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_supportticket_ticket_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRequestProxy',
        ),
    ]
