# Generated by Django 6.0.3 on 2026-05-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_payoutrequest_payout_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В обработке'), ('paid', 'Выплачено'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', max_length=20),
        ),
    ]
