# Generated by Django 6.0.3 on 2026-05-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_payoutrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
