# Generated by Django 6.0.3 on 2026-05-07 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_payoutrequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutrequest',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
    ]
