# Generated by Django 5.2 on 2026-08-05 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_sync_image_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_processing_status',
        ),
    ]
