# Generated by Django 6.0.3 on 2026-05-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_payoutrequest_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UTM Campaign'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_content',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UTM Content'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UTM Medium'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UTM Source'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_term',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UTM Term'),
        ),
    ]
