# Generated by Django 5.2 on 2026-08-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_event_image_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Отметьте, если это главное фото мероприятия', verbose_name='Основное фото'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='color',
            field=models.CharField(default='', help_text='Цвет отображается на странице покупки билета', max_length=7, verbose_name='Цвет билета'),
        ),
    ]
