# Generated by Django 6.0.3 on 2026-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderticket',
            name='is_refunded',
            field=models.BooleanField(default=False, verbose_name='Возвращён'),
        ),
    ]
