# Generated by Django 6.0.3 on 2026-05-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_customuser_video_business_card_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='video_processing_status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Обработка завершена'), ('failed', 'Ошибка обработки')], default='pending', max_length=20, verbose_name='Статус обработки видео'),
        ),
    ]
