# Generated by Django 6.0.3 on 2026-05-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_customuser_video_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Причина, по которой мероприятие было отклонено модератором', null=True, verbose_name='Причина отклонения'),
        ),
    ]
