# Generated by Django 5.2 on 2026-08-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_orderticket_is_refunded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payoutdetails',
            name='inn',
        ),
        migrations.AddField(
            model_name='payoutdetails',
            name='bik',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК банка'),
        ),
    ]
