# Generated by Django 5.2 on 2026-08-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_payoutdetails_inn_payoutdetails_bik'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Письмо отправлено'),
        ),
    ]
