# Generated by Django 6.0.3 on 2026-08-22 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_payoutdetails_inn_payoutdetails_bik'),
    ]

    operations = [
    ]
