# Generated by Django 5.2 on 2026-08-31 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_order_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(blank=True, help_text='Временный токен для сброса пароля по ссылке из письма', max_length=64, null=True, verbose_name='Токен восстановления пароля'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='main_tag',
            field=models.ForeignKey(help_text='Основной тег, к которому относится этот подтег', on_delete=django.db.models.deletion.CASCADE, related_name='subtags', to='core.maintag', verbose_name='Основной тег'),
        ),
    ]
