# Generated by Django 6.0.3 on 2026-05-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма комиссии платформы, удержанная с этого заказа', max_digits=10, verbose_name='Комиссия платформы'),
        ),
    ]
