# Generated by Django 6.0.3 on 2026-05-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_order_platform_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('succeeded', 'Оплачено'), ('canceled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус платежа'),
        ),
    ]
