# Generated by Django 5.2 on 2026-09-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_customuser_password_reset_token_alter_tag_main_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_description',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='Описание билета'),
        ),
    ]
