# Generated by Django 6.0.3 on 2026-05-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_type',
            field=models.CharField(choices=[('paid_ticket', 'Платный билет'), ('free_registration', 'Бесплатная регистрация'), ('platform_request', 'Заявка через платформу')], default='paid_ticket', max_length=20, verbose_name='Тип покупки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('succeeded', 'Оплачено'), ('canceled', 'Отменено'), ('refunded', 'Возврат')], default='pending', max_length=20, verbose_name='Статус платежа'),
        ),
    ]
