# Generated by Django 5.2 on 2026-09-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_ticket_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_description',
            field=models.TextField(default='', max_length=100, verbose_name='Описание билета'),
        ),
    ]
