# Generated by Django 5.2 on 2026-09-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_ticket_ticket_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpackagesubscription',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, help_text='Платёж, по которому подписка должна быть активирована', max_length=64, null=True, verbose_name='ID платежа ЮКассы'),
        ),
    ]
