# Generated by Django 5.2 on 2026-09-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_userpackagesubscription_yookassa_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpackagesubscription',
            name='yookassa_payment_id',
        ),
    ]
