# Generated by Django 5.2 on 2026-09-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_userpackagesubscription_yookassa_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fiscal_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Снимок payload чека, отправленного в кассу'),
        ),
        migrations.AddField(
            model_name='order',
            name='fiscal_receipt_error',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибка фискализации'),
        ),
        migrations.AddField(
            model_name='order',
            name='fiscal_receipt_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UUID фискального документа в Атоле'),
        ),
        migrations.AddField(
            model_name='order',
            name='fiscal_receipt_status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает фискализации'), ('succeeded', 'Чек пробит'), ('failed', 'Ошибка фискализации')], max_length=20, null=True, verbose_name='Статус фискализации'),
        ),
        migrations.AddField(
            model_name='order',
            name='principal_inn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН принципала'),
        ),
        migrations.AddField(
            model_name='order',
            name='principal_name',
            field=models.CharField(blank=True, help_text='Название организации-принципала на момент продажи', max_length=255, null=True, verbose_name='Принципал (наименование)'),
        ),
        migrations.AddField(
            model_name='order',
            name='principal_registration_type',
            field=models.CharField(blank=True, choices=[('physical', 'Физическое лицо'), ('legal', 'Юридическое лицо'), ('ip', 'ИП'), ('self_employed', 'Самозанятый')], max_length=20, null=True, verbose_name='Юр. статус принципала'),
        ),
    ]
