# Generated by Django 6.0.3 on 2026-09-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20260822_0319'),
        ('core', '0032_remove_userpackagesubscription_yookassa_payment_id'),
    ]

    operations = [
    ]
