# Generated by Django 6.0.3 on 2026-05-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_create_tag_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
    ]
