# Generated by Django 5.2 on 2026-09-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_order_fiscal_data_order_fiscal_receipt_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpackagesubscription',
            name='applicant_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email заявителя'),
        ),
        migrations.AddField(
            model_name='userpackagesubscription',
            name='applicant_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя заявителя'),
        ),
        migrations.AddField(
            model_name='userpackagesubscription',
            name='applicant_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Телефон заявителя'),
        ),
    ]
