# Generated by Django 6.0.3 on 2026-05-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Выберите до 5 тегов для мероприятия', to='core.tag', verbose_name='Теги'),
        ),
    ]
