# Generated by Django 6.0.3 on 2026-09-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_merge_20260915_1519'),
        ('core', '0033_order_fiscal_data_order_fiscal_receipt_error_and_more'),
    ]

    operations = [
    ]
