# Generated by Django 6.0.3 on 2026-05-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_codes',
            field=models.JSONField(blank=True, default=list, help_text='Список QR-кодов для каждого купленного билета', verbose_name='QR-коды'),
        ),
    ]
