# Generated by Django 5.2 on 2026-09-18 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_userpackagesubscription_applicant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackagesubscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала подписки'),
        ),
    ]
