# Generated by Django 6.0.3 on 2026-09-19 06:46

import core.document_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_userpackagesubscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания токена восстановления'),
        ),
        migrations.AlterField(
            model_name='supportattachment',
            name='file',
            field=models.FileField(storage=core.document_storage.YandexDocumentProcessingStorage(), upload_to='support_attachments/', verbose_name='Файл'),
        ),
    ]
