# Generated by Django 6.0.3 on 2026-05-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_order_qr_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_platform_requests',
            field=models.BooleanField(default=False, help_text='Если включено, пользователи смогут оставить заявку на участие вместо покупки билета', verbose_name='Разрешить заявки через платформу'),
        ),
    ]
