# Generated by Django 6.0.3 on 2026-09-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_customuser_password_reset_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Прочитано'),
        ),
    ]
