# Generated by Django 6.0.3 on 2026-05-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_event_allow_platform_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='allow_platform_requests',
            field=models.BooleanField(default=False, help_text='Если включено, пользователи смогут оставить заявку с вопросами', verbose_name='Разрешить заявки через платформу'),
        ),
    ]
