# Generated by Django 6.0.3 on 2026-09-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_merge_20260916_1525'),
        ('core', '0037_supportmessage_is_read'),
    ]

    operations = [
    ]
