# Generated by Django 6.0.3 on 2026-05-16 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_event_allow_platform_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequestProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Заявка на мероприятие',
                'verbose_name_plural': 'Заявки на мероприятия',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.supportticket',),
        ),
    ]
