# Generated by Django 6.0.3 on 2026-09-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_merge_20260920_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Сообщение поддержки', 'verbose_name_plural': 'Сообщения поддержки'},
        ),
    ]
