# Generated by Django 6.0.3 on 2026-05-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_eventrequestproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('succeeded', 'Оплачено'), ('canceled', 'Отменено'), ('refunded', 'Возврат'), ('reserved', 'Забронировано')], default='pending', max_length=20, verbose_name='Статус платежа'),
        ),
    ]
