# Generated by Django 5.2 on 2026-09-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='consent_marketing',
            field=models.BooleanField(default=False, verbose_name='Согласие на рассылку'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='consent_marketing_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия на рассылку'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='consent_personal_data',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='consent_personal_data_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия на обработку ПД'),
        ),
    ]
