# Generated by Django 6.0.3 on 2026-05-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='yookassa_payment_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные платежа из ЮКассы'),
        ),
    ]
