# Generated by Django 6.0.3 on 2026-05-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_order_yookassa_payment_data_and_more'),
    ]

    operations = [
    ]
