# Generated by Django 6.0.3 on 2026-09-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_stale_userconsent_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Код страницы')),
                ('title', models.CharField(help_text='Видно только в админке — на сайте заголовок задаёт шаблон', max_length=200, verbose_name='Название')),
                ('content', models.TextField(blank=True, verbose_name='Текст страницы (HTML)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Юридическая страница',
                'verbose_name_plural': 'Юридические страницы',
                'ordering': ('title',),
            },
        ),
    ]
