# Generated by Django 6.0.3 on 2026-05-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_fix_yookassa_payment_id'),
    ]

    operations = [
    ]
