# Generated by Django 5.2 on 2026-05-22 11:12

from django.db import migrations

def remove_orderitem_table(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("DROP TABLE IF EXISTS core_orderitem CASCADE;")
    else:
        schema_editor.execute("DROP TABLE IF EXISTS core_orderitem;")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_fix_yookassa_payment_id_duplicate'),
    ]

    operations = [
        migrations.RunPython(remove_orderitem_table),
    ]