# Generated by Django 6.0.3 on 2026-05-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_orderitem_table'),
    ]

    operations = [
    ]
