# Generated by Django 6.0.3 on 2026-05-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_orderitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор платежа в ЮКассе'),
        ),
    ]
