# Generated by Django 6.0.3 on 2026-09-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_seed_legal_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Адрес электронной почты'),
        ),
    ]
