# Generated by Django 5.2 on 2026-09-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_emailverificationcode_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя отправка кода подтверждения'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_send_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество отправок кода'),
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия кода'),
        ),
    ]
