# Generated by Django 6.0.3 on 2026-10-08 08:49

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_customuser_last_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpackage',
            name='max_description_length',
            field=models.PositiveIntegerField(default=1500, help_text='Укажите максимальное количество символов в описании мероприятий этого пакета.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум символов в описании мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Лимит символов определяется пакетом мероприятия', verbose_name='Описание'),
        ),
    ]
