# Generated by Django 6.0.3 on 2026-05-24 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_fix_yookassa_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название основного тега')),
            ],
            options={
                'verbose_name': 'Основной тег',
                'verbose_name_plural': 'Основные теги',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                apps.get_model('core', 'MainTag').objects.create(
                    id=1,
                    name='Без категории'
                )
            ),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['main_tag__name', 'name'], 'verbose_name': 'Подтег', 'verbose_name_plural': 'Подтеги'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название подтега'),
        ),
        migrations.AddField(
            model_name='tag',
            name='main_tag',
            field=models.ForeignKey(default=1, help_text='Основной тег, к которому относится этот подтег', on_delete=django.db.models.deletion.CASCADE, related_name='subtags', to='core.maintag', verbose_name='Основной тег'),
        ),
    ]
