# Generated by Django 6.0.3 on 2026-10-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_eventpackage_max_description_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_font_size',
            field=models.PositiveSmallIntegerField(choices=[(13, '13 px — стандартный размер'), (14, '14 px — немного крупнее'), (15, '15 px — крупнее'), (16, '16 px — большой'), (17, '17 px — ещё больше'), (18, '18 px — очень большой'), (19, '19 px — почти максимальный'), (20, '20 px — максимальный')], default=13, help_text='Выберите размер текста на странице мероприятия. 13 px — стандартный размер, максимальный — 20 px.', verbose_name='Размер текста описания'),
        ),
    ]
