# Generated by Django 6.0.3 on 2026-05-24 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_maintag_alter_tag_options_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название пакета')),
                ('max_active_events', models.PositiveIntegerField(default=1, verbose_name='Максимум активных мероприятий')),
                ('event_card_type', models.CharField(choices=[('basic', 'Базовая'), ('extended', 'Расширенная'), ('priority', 'Приоритетная')], default='basic', max_length=20, verbose_name='Тип карточки события')),
                ('description_type', models.CharField(choices=[('short', 'Краткое'), ('detailed', 'Подробное')], default='short', max_length=20, verbose_name='Тип описания')),
                ('has_program_and_speakers', models.BooleanField(default=True, verbose_name='Программа и спикеры')),
                ('max_photos', models.PositiveIntegerField(default=1, verbose_name='Максимум фото')),
                ('has_video', models.BooleanField(default=False, verbose_name='Видео')),
                ('has_platform_request', models.BooleanField(default=True, verbose_name='Заявка внутри платформы')),
                ('has_free_registration', models.BooleanField(default=True, verbose_name='Зарегистрироваться (бесплатное мероприятие)')),
                ('has_ticket_sales', models.BooleanField(default=True, verbose_name='Покупка билета')),
                ('visibility_level', models.CharField(choices=[('basic', 'Базовая'), ('enhanced', 'Повышенная'), ('priority', 'Приоритетная')], default='basic', max_length=20, verbose_name='Видимость в каталоге')),
                ('has_collection_participation', models.BooleanField(default=False, verbose_name='Участие в подборках')),
            ],
            options={
                'verbose_name': 'Пакет мероприятия',
                'verbose_name_plural': 'Пакеты мероприятий',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Выберите пакет для мероприятия', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventpackage', verbose_name='Пакет мероприятия'),
        ),
    ]
