# Generated by Django 6.0.3 on 2026-05-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_eventimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
