# Generated by Django 6.0.3 on 2026-05-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо (ФИО)'),
        ),
    ]
