# Generated by Django 6.0.3 on 2026-05-27 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpackage',
            name='is_monthly',
            field=models.BooleanField(default=False, verbose_name='Ежемесячная подписка'),
        ),
        migrations.CreateModel(
            name='UserPackageSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала подписки')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания подписки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('subscription_type', models.CharField(choices=[('one_time', 'Разовая покупка'), ('monthly', 'Ежемесячная подписка')], default='one_time', max_length=20, verbose_name='Тип подписки')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eventpackage', verbose_name='Пакет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на пакет',
                'verbose_name_plural': 'Подписки на пакеты',
            },
        ),
    ]
