# Generated by Django 6.0.3 on 2026-05-28 12:22

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_eventpackage_is_monthly_userpackagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonPartnerUser',
            fields=[
            ],
            options={
                'verbose_name': 'Не-партнёр',
                'verbose_name_plural': 'Не-партнёры',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='userpackagesubscription',
            name='subscription_type',
        ),
        migrations.AddField(
            model_name='eventpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена пакета'),
        ),
    ]
