# Generated by Django 5.2 on 2026-05-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_nonpartneruser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpackagesubscription',
            name='subscription_type',
            field=models.CharField(choices=[('monthly', 'Ежемесячная подписка')], default='one_time', max_length=20, verbose_name='Тип подписки'),
        ),
    ]
