# Generated by Django 6.0.3 on 2026-05-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_userpackagesubscription_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackagesubscription',
            name='subscription_type',
            field=models.CharField(choices=[('monthly', 'Ежемесячная подписка')], default='monthly', max_length=20, verbose_name='Тип подписки'),
        ),
    ]
