# Generated by Django 6.0.3 on 2026-05-31 08:35

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_userpackagesubscription_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Изображение'),
        ),
    ]