# Generated by Django 6.0.3 on 2026-05-31 08:41

import core.models
import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_add_event_image_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/', verbose_name='Фото мероприятия')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Фото мероприятия',
                'verbose_name_plural': 'Фото мероприятий',
            },
            bases=(core.models.VideoWatermarkMixin, models.Model),
        ),
    ]