# Generated by Django 6.0.3 on 2026-06-06 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_recreate_eventimage_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpackagesubscription',
            name='scheduled_change_date',
            field=models.DateTimeField(blank=True, help_text='Дата, когда должен вступить в силу запланированный пакет', null=True, verbose_name='Дата запланированного изменения'),
        ),
        migrations.AddField(
            model_name='userpackagesubscription',
            name='scheduled_change_to',
            field=models.ForeignKey(blank=True, help_text='Пакет, на который будет переключена подписка после окончания текущей', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_subscriptions', to='core.eventpackage', verbose_name='Запланированный пакет'),
        ),
        migrations.AlterField(
            model_name='userpackagesubscription',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_subscriptions', to='core.eventpackage', verbose_name='Пакет'),
        ),
        migrations.AlterField(
            model_name='userpackagesubscription',
            name='subscription_type',
            field=models.CharField(choices=[('monthly', 'Ежемесячная подписка'), ('one_time', 'Разовый пакет')], default='monthly', max_length=20, verbose_name='Тип подписки'),
        ),
    ]
