# Generated by Django 6.0.3 on 2026-06-12 08:06

import core.image_storage
import core.video_storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_userpackagesubscription_scheduled_change_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='video_business_card',
            field=models.FileField(blank=True, help_text='Максимальная длительность видео: 5 минут.', null=True, upload_to='partner_video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])], verbose_name='Видео (загрузить)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.image_storage.YandexImageProcessingStorage(), upload_to='event_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='video_url',
            field=models.FileField(blank=True, help_text='Максимальная длительность видео: 5 минут.', null=True, storage=core.video_storage.YandexVideoProcessingStorage(), upload_to='event_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])], verbose_name='Видео (загрузить)'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(storage=core.image_storage.YandexImageProcessingStorage(), upload_to='event_images/', verbose_name='Фото мероприятия'),
        ),
    ]
