# Generated by Django 6.0.3 on 2026-06-13 05:37

import core.document_storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_customuser_video_business_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название формата')),
            ],
            options={
                'verbose_name': 'Формат',
                'verbose_name_plural': 'Форматы',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='program_file',
            field=models.FileField(blank=True, null=True, storage=core.document_storage.YandexDocumentProcessingStorage(), upload_to='event_programs/', verbose_name='Программа (PDF)'),
        ),
        migrations.AddField(
            model_name='event',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.format', verbose_name='Формат'),
        ),
    ]
