# Generated by Django 5.2 on 2026-06-15 04:04

import core.document_storage
import core.video_storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_format_alter_event_program_file_event_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='video_business_card',
            field=models.FileField(blank=True, help_text='Максимальная длительность видео: 5 минут.', null=True, storage=core.video_storage.YandexVideoProcessingStorage(), upload_to='partner_video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])], verbose_name='Видео (загрузить)'),
        ),
        migrations.AlterField(
            model_name='partnerdocument',
            name='document',
            field=models.FileField(storage=core.document_storage.YandexDocumentProcessingStorage(), upload_to='partner_documents/', verbose_name='Документ'),
        ),
    ]
