# Generated by Django 5.2 on 2026-06-15 04:26

import core.image_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_customuser_video_business_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=core.image_storage.YandexImageProcessingStorage(), upload_to='user_logos/'),
        ),
    ]
