# Generated by Django 5.2 on 2026-06-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_customuser_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerdocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Документ партнёра', 'verbose_name_plural': 'Документы партнёров'},
        ),
        migrations.AddField(
            model_name='partnerdocument',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения'),
        ),
    ]
