# Generated by Django 6.0.3 on 2026-06-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_partnerdocument_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NonPartnerUser',
        ),
        migrations.AlterField(
            model_name='userpackagesubscription',
            name='subscription_type',
            field=models.CharField(choices=[('monthly', 'Ежемесячная подписка')], default='monthly', max_length=20, verbose_name='Тип подписки'),
        ),
    ]
