# Generated by Django 6.0.3 on 2026-06-16 17:26

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_delete_nonpartneruser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorUser',
            fields=[
            ],
            options={
                'verbose_name': 'Обычный пользователь',
                'verbose_name_plural': 'Обычные пользователи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='qr_codes_generated',
            field=models.BooleanField(default=False, verbose_name='QR-коды сгенерированы'),
        ),
    ]
