# Generated by Django 5.2 on 2026-06-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_visitoruser_order_qr_codes_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qr_codes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qr_codes_generated',
        ),
    ]
