# Generated by Django 5.2 on 2026-04-18 14:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='weekly', max_length=10, verbose_name='Частота')),
                ('report_format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('excel', 'Excel')], default='pdf', max_length=10, verbose_name='Формат отчёта')),
                ('period_type', models.CharField(choices=[('day', 'За день'), ('week', 'За неделю'), ('month', 'За месяц'), ('custom', 'Произвольный период')], default='week', max_length=10, verbose_name='Период отчёта')),
                ('email', models.EmailField(max_length=254, verbose_name='Email для отправки')),
                ('day_of_week', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(6)], verbose_name='День недели (0-6)')),
                ('day_of_month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(31)], verbose_name='День месяца (1-31)')),
                ('custom_period_days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество дней для произвольного периода')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Последняя отправка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedule', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Расписание отчётов',
                'verbose_name_plural': 'Расписания отчётов',
            },
        ),
    ]
