# Generated by Django 6.0.3 on 2026-06-19 09:00

import core.document_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='file_path',
            field=models.FileField(storage=core.document_storage.YandexDocumentProcessingStorage(), upload_to='reports/', verbose_name='Файл отчёта'),
        ),
    ]
