# Generated by Django 5.2 on 2026-06-25 09:45

import core.video_storage
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0002_alter_salesreport_file_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('physical', 'Физическое лицо'), ('legal', 'Юридическое лицо'), ('ip', 'ИП'), ('self_employed', 'Самозанятый')], default='legal', max_length=20, verbose_name='Тип лица')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название организации / ФИО')),
                ('short_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое наименование, бренд/торговое имя')),
                ('description', models.TextField(blank=True, help_text='Кратко о деятельности', max_length=500, null=True, verbose_name='Описание организации (до 500 символов)')),
                ('ogrn', models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН/ОГРНИП')),
                ('inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('legal_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Юридический адрес')),
                ('actual_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фактический адрес')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт компании URL')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо (ФИО)')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('social_links', models.TextField(blank=True, null=True, verbose_name='Социальные сети')),
                ('vk_link', models.URLField(blank=True, null=True, verbose_name='VK')),
                ('max_link', models.URLField(blank=True, null=True, verbose_name='MAX')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('cases', models.TextField(blank=True, help_text='Ссылки или краткое описание', null=True, verbose_name='Кейсы/прошедшие мероприятия')),
                ('reviews', models.TextField(blank=True, help_text='Ссылки', null=True, verbose_name='Отзывы и публикации в СМИ')),
                ('logo', models.ImageField(blank=True, help_text='До 5 МБ', null=True, upload_to='partner_logos/', verbose_name='Логотип (PNG/SVG/JPG)')),
                ('video_business_card', models.FileField(blank=True, help_text='Максимальная длительность видео: 5 минут.', null=True, storage=core.video_storage.YandexVideoProcessingStorage(), upload_to='partner_video/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi'])], verbose_name='Видео-визитка')),
                ('processed_video_business_card_hash', models.CharField(blank=True, max_length=32, null=True, verbose_name='Хэш обработанного видео')),
                ('video_business_card_processing_status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Обработка завершена'), ('failed', 'Ошибка обработки')], default='pending', max_length=20, verbose_name='Статус обработки видео-визитки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Профиль партнёра',
                'verbose_name_plural': 'Профили партнёров',
                'ordering': ['-created_at'],
            },
        ),
    ]
