# Generated by Django 6.0.3 on 2026-04-18 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0002_reportschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportschedule',
            name='day_of_week',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='День недели (0-6)'),
        ),
    ]
