# Generated by Django 5.2 on 2026-06-15 04:04

import core.document_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0003_alter_reportschedule_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='file_path',
            field=models.FileField(storage=core.document_storage.YandexDocumentProcessingStorage(), upload_to='reports/', verbose_name='Файл отчёта'),
        ),
    ]
