# Generated by Django 5.2 on 2026-06-26 10:39

import core.image_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0003_partnerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='До 5 МБ', null=True, storage=core.image_storage.YandexImageProcessingStorage(), upload_to='partner_logos/', verbose_name='Логотип (PNG/SVG/JPG)'),
        ),
    ]
