# Generated by Django 5.2 on 2026-06-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0004_alter_partnerprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='additional_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Дополнительный E-mail'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail (для входа)'),
        ),
    ]
