# Generated by Django 5.2 on 2026-07-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0005_partnerprofile_additional_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс'),
        ),
    ]
