# Generated by Django 5.2 on 2026-07-30 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0006_partnerprofile_postal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='До 100 символов', max_length=100, verbose_name='Название')),
                ('event_date', models.DateField(verbose_name='Дата проведения')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('description', models.TextField(help_text='До 1500 символов', max_length=1500, verbose_name='Описание')),
                ('links', models.JSONField(blank=True, default=list, help_text='До 3 ссылок (статьи, СМИ, соцсети)', verbose_name='Ссылки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('partner', models.ForeignKey(limit_choices_to={'user_type': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Элемент портфолио',
                'verbose_name_plural': 'Элементы портфолио',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_images/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='partner_app.portfolioitem', verbose_name='Портфолио')),
            ],
            options={
                'verbose_name': 'Изображение портфолио',
                'verbose_name_plural': 'Изображения портфолио',
                'ordering': ['order'],
            },
        ),
    ]
