# Generated by Django 5.2 on 2026-07-30 12:05

import core.image_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0007_portfolioitem_portfolioimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.ImageField(storage=core.image_storage.YandexImageProcessingStorage(), upload_to='portfolio_images/', verbose_name='Изображение'),
        ),
    ]
