# Generated by Django 6.0.3 on 2026-07-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0008_alter_portfolioimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='description',
            field=models.TextField(help_text='До 1000 символов', max_length=1000, verbose_name='Описание'),
        ),
    ]
