# Generated by Django 5.2 on 2026-08-18 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_orderticket_is_refunded'),
        ('partner_app', '0009_alter_portfolioitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAccessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(help_text='Уникальный короткий код для страницы сканера', max_length=16, unique=True, verbose_name='Код доступа')),
                ('is_active', models.BooleanField(default=True, help_text='Если отключён — сканер не работает', verbose_name='Активен')),
                ('scanned_count', models.PositiveIntegerField(default=0, verbose_name='Отсканировано билетов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Активирован')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Деактивирован')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_link', to='core.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Ссылка контроля входа',
                'verbose_name_plural': 'Ссылки контроля входа',
                'ordering': ['-created_at'],
            },
        ),
    ]
