# Generated by Django 5.2 on 2026-08-18 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_orderticket_is_refunded'),
        ('partner_app', '0010_eventaccesslink'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventaccesslink',
            name='name',
            field=models.CharField(blank=True, help_text="Например: 'Контролёр Алексей — вход №1'", max_length=100, verbose_name='Имя контролёра'),
        ),
        migrations.AlterField(
            model_name='eventaccesslink',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_links', to='core.event', verbose_name='Мероприятие'),
        ),
    ]
