# Generated by Django 5.2 on 2026-08-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0011_eventaccesslink_name_alter_eventaccesslink_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventaccesslink',
            name='name',
            field=models.CharField(blank=True, help_text="Например: 'Контролёр Алексей — вход №1'", max_length=100, null=True, verbose_name='Имя контролёра'),
        ),
    ]
