# Generated by Django 5.2 on 2026-09-02 08:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_customuser_password_reset_token_alter_tag_main_tag'),
        ('partner_app', '0012_alter_eventaccesslink_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Изменения полей')),
                ('tickets_data', models.JSONField(blank=True, default=list, verbose_name='Предложенные билеты')),
                ('tag_ids', models.JSONField(blank=True, default=list, verbose_name='ID тегов')),
                ('new_image', models.ImageField(blank=True, null=True, upload_to='change_requests/images/', verbose_name='Новое основное изображение')),
                ('new_video_url', models.FileField(blank=True, null=True, upload_to='change_requests/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi'])], verbose_name='Новое видео')),
                ('new_program_file', models.FileField(blank=True, null=True, upload_to='change_requests/programs/', verbose_name='Новая программа (PDF)')),
                ('clear_image', models.BooleanField(default=False, verbose_name='Удалить основное фото')),
                ('clear_video_url', models.BooleanField(default=False, verbose_name='Удалить видео')),
                ('clear_program_file', models.BooleanField(default=False, verbose_name='Удалить программу')),
                ('delete_image_ids', models.JSONField(blank=True, default=list, verbose_name='ID фото галереи к удалению')),
                ('primary_image_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID фото галереи, которое сделать основным')),
                ('primary_new_image_index', models.PositiveIntegerField(blank=True, null=True, verbose_name='Индекс нового фото, которое сделать основным')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий администратора')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='core.event', verbose_name='Мероприятие')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_event_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кто рассмотрел')),
            ],
            options={
                'verbose_name': 'Заявка на изменение мероприятия',
                'verbose_name_plural': 'Заявки на изменение мероприятий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventChangeRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='change_requests/gallery/', verbose_name='Фото')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_gallery_images', to='partner_app.eventchangerequest', verbose_name='Заявка на изменение')),
            ],
            options={
                'verbose_name': 'Фото заявки на изменение',
                'verbose_name_plural': 'Фото заявок на изменение',
                'ordering': ['id'],
            },
        ),
    ]
