# Generated by Django 6.0.3 on 2026-09-03 09:43

import core.video_storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0013_eventchangerequest_eventchangerequestimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventchangerequest',
            name='new_video_url',
            field=models.FileField(blank=True, null=True, storage=core.video_storage.YandexVideoProcessingStorage(subdirectory='change_request_videos'), upload_to='change_requests/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi'])], verbose_name='Новое видео'),
        ),
    ]
