# Generated by Django 5.2 on 2026-09-08 10:43

import core.validators
import core.video_storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0014_alter_eventchangerequest_new_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerprofile',
            name='video_business_card',
            field=models.FileField(blank=True, help_text='Максимальная длительность видео: 5 минут.', null=True, storage=core.video_storage.YandexVideoProcessingStorage(), upload_to='partner_video/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi']), core.validators.validate_video_duration], verbose_name='Видео-визитка'),
        ),
    ]
