# Generated by Django 6.0.3 on 2026-09-19 06:49

import core.document_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0015_alter_partnerprofile_video_business_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventchangerequest',
            name='new_program_file',
            field=models.FileField(blank=True, null=True, storage=core.document_storage.YandexDocumentProcessingStorage(), upload_to='change_requests/programs/', verbose_name='Новая программа (PDF)'),
        ),
    ]
