# Generated by Django 5.2 on 2026-09-27 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0016_alter_eventchangerequest_new_program_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер отчёта')),
                ('period_year', models.PositiveIntegerField(verbose_name='Год отчётного периода')),
                ('period_month', models.PositiveIntegerField(verbose_name='Месяц отчётного периода')),
                ('file_path', models.FileField(upload_to='agent_reports/', verbose_name='Файл отчёта')),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Валовая выручка (принято от покупателей)')),
                ('refunds_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Возвраты покупателям')),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Чистая выручка')),
                ('agent_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Вознаграждение агента')),
                ('payable_to_principal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='К перечислению принципалу')),
                ('receipts_count', models.PositiveIntegerField(default=0, verbose_name='Сформировано кассовых чеков')),
                ('receipts_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма по кассовым чекам')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата формирования')),
                ('partner', models.ForeignKey(limit_choices_to={'user_type': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_reports', to=settings.AUTH_USER_MODEL, verbose_name='Принципал (организатор)')),
            ],
            options={
                'verbose_name': 'Отчёт агента',
                'verbose_name_plural': 'Отчёты агента',
                'ordering': ['-period_year', '-period_month'],
                'constraints': [models.UniqueConstraint(fields=('partner', 'period_year', 'period_month'), name='unique_agent_report_per_period')],
            },
        ),
    ]
