# Generated by Django 5.2 on 2026-09-27 15:52

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0017_agentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='agent_contract_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='Номер агентского договора'),
        ),
        migrations.AlterField(
            model_name='agentreport',
            name='file_path',
            field=models.FileField(storage=core.storage_backends.YandexCloudWithProcessingStorage(), upload_to='agent_reports/', verbose_name='Файл отчёта'),
        ),
    ]
